(!window.btoa||!window.atob)&&window.alert("You are using an old version of your browser that is no longer supported by Vudu. Please upgrade your browser to a more recent version.");var VUDU=window.VUDU||{};VUDU.jsUtil=VUDU.jsUtil||{};if(!VUDU.configs.enableMyOffers)document.getElementById("topNavOffers").style.display="none";
var cleanUpMyVudu=function(){return{setCleanUpMyVuduFlag:function(a){this.cleanUpMyVuduFlag=a},doCleanUpMyVudu:function(){if(this.cleanUpMyVuduFlag)for(var a=document.cookie.split(";"),b=a.length,c=0;c<b;c++){var d=a[c].split("=")[0];d.indexOf("myvudu")!=-1&&deleteCookie(d,VUDU.environment.cookieDomain)}}}}(),_vuduSearchDiv=document.getElementById("topNavSearch"),_vuduSearchField=_vuduSearchDiv.getElementsByTagName("input")[0],_vuduSearchFieldWidth=45,_vuduSearchFieldWidthShiftPixels=15,obfuscate=
function(a){return encodeURIComponent(btoa(unescape(encodeURIComponent(a))))},unobfuscate=function(a){return"undefined"==typeof a?"":decodeURIComponent(escape(atob(decodeURIComponent(a))))},_vuduGetCookieTemporary=function(a){if(document.cookie&&document.cookie.length>0){var b=document.cookie.indexOf(a+"=");if(b==-1)return null;b+=a.length+1;a=document.cookie.indexOf(";",b);if(a==-1)a=document.cookie.length;b=decodeURIComponent(escape(document.cookie.substr(b,a-b)));return decodeURIComponent(b)}return null},
_vuduGetCookie=function(a){var b=a,a=obfuscate(a);if(document.cookie&&document.cookie.length>0){var c=document.cookie.indexOf(a+"=");if(c==-1)return _vuduGetCookieTemporary(b);c+=a.length+1;a=document.cookie.indexOf(";",c);if(a==-1)a=document.cookie.length;return unobfuscate(document.cookie.substr(c,a-c))}return null},_vuduDeleteCookie=function(a,b){_vuduGetCookie(a)&&deleteCookie(a,b)},deleteCookie=function(a,b){document.cookie=a+"=;path=/;"+(b?"domain="+b+";":"")+"expires=Thu, 01-Jan-1970 00:00:01 GMT;"},
_vuduUpdateLoginStatus=function(){cleanUpMyVudu.doCleanUpMyVudu();var a="",b="vudu-nav",c=_vuduGetCookie("myvudu.sessionKey");if(c){b+=" logedIn";a=_vuduGetCookie("myvudu.displayName").replace(/[\"\\\+\*\?\[\^\]\$\(\)\{\}\=\!<>\|\:]/g,"\\$&");if(a==null||a=="_"||a==""||a=="null"||a=="undefined")a=_vuduGetCookie("myvudu.userName").replace(/[\"\\\+\*\?\[\^\]\$\(\)\{\}\=\!<>\|\:]/g,"\\$&");if(a==null||a=="_"||a==""||a=="null"||a=="undefined")a="My Account"}if(document.getElementById("topNavVuduNav")!=
null)document.getElementById("topNavVuduNav").className=b;if(document.getElementById("topNavUsername")!=null)document.getElementById("topNavUsername").innerHTML=a;a=document.getElementById("topNavUserPicContainer");if(a!=null){for(;a.firstChild;)a.removeChild(a.firstChild);b=_vuduGetCookie("myvudu.fbUserId");if(VUDU.configs.allowFacebookLogin&&c&&b!=null&&b!="null")c=document.createElement("img"),c.src="//graph.facebook.com/"+b+"/picture?type=square",c.className="showUserPic",c.alt="User image",a.appendChild(c)}},
_vuduUpdateStatusLogout=function(a){_vuduDeleteCookie("myvudu.userName",a);_vuduDeleteCookie("myvudu.userName",a);_vuduDeleteCookie("myvudu.userId",a);_vuduDeleteCookie("myvudu.fbUserId",a);_vuduDeleteCookie("myvudu.sessionKey",a);_vuduDeleteCookie("myvudu.sessionAuthType",a);window.location.reload()},_vuduFullLogout=function(){VUDU.jsUtil.logout()},_vuduSearchFieldAnimate=function(a){_vuduSearchFieldWidth+=(a?-1:1)*_vuduSearchFieldWidthShiftPixels;_vuduSearchField.style.width=_vuduSearchFieldWidth+
"px";_vuduSearchDiv.className=_vuduSearchFieldWidth>6*_vuduSearchFieldWidthShiftPixels?"active":"";_vuduSearchFieldWidth<8*_vuduSearchFieldWidthShiftPixels&&_vuduSearchFieldWidth>30&&setTimeout("_vuduSearchFieldAnimate("+a+")",40)};_vuduSearchField.onfocus=function(){};_vuduSearchField.onblur=function(){};_vuduSearchField.onkeypress=function(a){if(window.event)a=window.event;if(a.keyCode==13)document.location.href=VUDU.environment.wwwHome+"movies/search/"+_vuduSearchField.value};
var _vuduImagePreload=function(){var a=new Image;if(_vuduImagePreload.arguments.length>0)for(var b=0;b<_vuduImagePreload.arguments.length;b++)a.src=(window.location.protocol.indexOf("https")==-1&&window.location.protocol.indexOf("HTTPS")==-1?VUDU.environment.wwwHome:VUDU.environment.myHome)+_vuduImagePreload.arguments[b]},_getUrlParam=function(a){for(var b=location.search.substr(location.search.indexOf("?")+1),c="",b=b.split("&"),c=0;c<b.length;c++)if(temp=b[c].split("="),temp[0].toLowerCase()==a.toLowerCase())return c=
temp[1],unescape(c);return null},_vuduStoreCookie=function(a,b,c){var d=window.ipadCookieDomain?window.ipadCookieDomain:VUDU.config?VUDU.config.cookieDomain:accountConfig.cookieDomain,e=new Date;e.setDate(e.getDate()+c);b=obfuscate(b)+"; expires="+e.toUTCString()+"; path=/; domain="+d;document.cookie=obfuscate(a)+"="+b},_vuduStoreReferrerCookies=function(){if(document.referrer&&document.referrer.length>0){var a=document.referrer.match(/:\/\/(.[^/]+)/)[1];a.indexOf(window.ipadCookieDomain?window.ipadCookieDomain:
VUDU.config?VUDU.config.cookieDomain:accountConfig.cookieDomain)<0&&_vuduStoreCookie("myvudu.referringDomain",a,90)}if((a=_getUrlParam("cid"))&&a.length>0){var b=_getUrlParam("scid"),c=_getUrlParam("kwid"),d=_getUrlParam("adid");_vuduStoreCookie("myvudu.campaignId",a+"-"+b+"-"+c+"-"+d,90)}};VUDU.jsUtil.signIn=function(){var a=VUDU.urls.signInPage,b=window.location.href;a+=(a.indexOf("?")!=-1?"&":"?")+"url="+encodeURIComponent(b);window.location.assign(a)};VUDU.jsUtil.signUp=function(){window.location.assign(VUDU.urls.signUpPage)};
VUDU.jsUtil.logout=function(){var a=VUDU.urls.logoutPage,b;b=window.location.href.indexOf(VUDU.environment.myHome)==0?escape(VUDU.urls.moviesPage):escape(window.location.href);window.location.assign(a+(a.indexOf("?")!=-1?"&":"?")+"url="+b)};
VUDU.isSupportedPhone=function(){var a=!1;if(navigator.userAgent.indexOf("iPhone")!=-1||navigator.userAgent.indexOf("iPod")!=-1)a=!0;else if(navigator.userAgent.indexOf("Android")!=-1&&(navigator.userAgent.indexOf("Mobile")!=-1||navigator.userAgent.indexOf("Opera Mobi")!=-1))a=!0;return a};VUDU.isTouchDevice=function(){return navigator.userAgent.indexOf("iPhone")!=-1||navigator.userAgent.indexOf("iPod")!=-1||navigator.userAgent.indexOf("iPad")!=-1||navigator.userAgent.indexOf("Android")!=-1};
VUDU.isTabletDevice=function(){return navigator.userAgent.indexOf("iPad")!=-1||navigator.userAgent.indexOf("Android")!=-1&&navigator.userAgent.indexOf("Mobile")==-1};
if(VUDU.isTouchDevice()){var header=document.getElementsByClassName("vudu-header");if(header&&header[0])header[0].style.position="absolute";document.getElementById("topNavAccount")!=null&&document.getElementById("topNavAccount").addEventListener("touchend",function(){this.querySelector("div.subMenu").style.display="block"},!1);window.addEventListener("touchend",function(a){if(document.getElementById("topNavAccount")!=null&&matchParent(a.target,document.getElementById("topNavAccount"))==null)document.getElementById("topNavAccount").querySelector("div.subMenu").style.display=
"none"},!0);var matchParent=function(a,b){for(var c=a.parentNode;null!=c&&c!=b;)if(c=c.parentNode,c==document.body)return null;return c}}
var _vuduUpdateChromecastDevicePageStatus=function(){var a=document.getElementById("action-chromecast"),b=document.getElementById("topNavChromecast"),c=document.getElementById("topNavChromecastFooter");if(VUDU.configs.enableChromecastDevicePage){if(a)a.style.display="block";if(b)b.style.display="block";if(c)c.style.display="block"}else{if(a)a.style.display="none";if(b)b.style.display="none";if(c)c.style.display="none"}},getExpirationLabel=function(a){var b=Date.now(),c=a-b;return c<0?"Offer Expired":
a-b>=864E5?"Expires in "+Math.ceil(c/864E5)+" days":c>36E5?"Expires in "+Math.ceil(c/36E5)+" hours":"Expires in "+Math.ceil(c/6E4)+" minutes"},populateOffers=function(){document.getElementById("offers-icon").className="";if(VUDU.myOffers)if(VUDU.myOffers.length>0){document.getElementById("topNavOffers").className="has-offers";for(var a=0;a<Math.min(3,VUDU.myOffers.length);a++)(function(a){var c=a+1;document.getElementById("offer-"+c+"-title").innerHTML=VUDU.myOffers[a].notificationText;document.getElementById("offer-"+
c+"-expiration").innerHTML=getExpirationLabel(VUDU.myOffers[a].expiration);VUDU.myOffers[a].viewed?document.getElementById("offer-"+c).className="offer viewed":(document.getElementById("offers-icon").className="has-unread-offers",document.getElementById("offer-"+c).className="offer");if(VUDU.myOffers[a].linkUrl)document.getElementById("offer-"+c).onclick=function(){VUDU.hideOffersPopup();VUDU.myOffersUtil.trackBenefitClicked&&VUDU.myOffersUtil.trackBenefitClicked(VUDU.myOffers[a].targetGroupId,VUDU.myOffers[a].userSegmentId);
window.location.assign(VUDU.myOffers[a].linkUrl)};document.getElementById("offer-"+c).style.display="block"})(a);for(a=VUDU.myOffers.length;a<3;a++)document.getElementById("offer-"+(a+1)).style.display="none";return!0}else return document.getElementById("topNavOffers").className="",!1},hideOffersTimer;VUDU.hideOffersPopup=function(){window.clearTimeout(hideOffersTimer);hideOffersTimer=window.setTimeout(function(){document.getElementById("offers-popup").style.display="none"},300)};
VUDU.cancelHideOffersTimer=function(){window.clearTimeout(hideOffersTimer)};VUDU.showOffersPopup=function(){if(VUDU.myOffers)window.clearTimeout(hideOffersTimer),populateOffers()||VUDU.myOffersUtil.trackNoOffers&&VUDU.myOffersUtil.trackNoOffers(),document.getElementById("offers-popup").style.display="block",VUDU.myOffersUtil.trackOffersOpen&&VUDU.myOffersUtil.trackOffersOpen()};
VUDU.goToMyOffers=function(){VUDU.myOffersUtil&&VUDU.myOffersUtil.trackSeeAllOffersClicked&&VUDU.myOffersUtil.trackSeeAllOffersClicked();VUDU.hideOffersPopup();window.location.assign(VUDU.urls.myOffers)};VUDU.updateMyOffers=function(a,b){if(document.getElementById("offers-popup"))VUDU.myOffers=b,populateOffers()};_vuduImagePreload("images/repeating/top-menu-active-center.png","images/repeating/top-menu-hover-center.png");_vuduUpdateLoginStatus();_vuduStoreReferrerCookies();_vuduUpdateChromecastDevicePageStatus();